import type { Metadata } from "next";
import "./globals.css";
import montserrat from "./fonts";

import Header from "./ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} subpixel-antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
